version: '3.9'
services:
  ## Vue Frontend
  frontend:
    container_name: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    restart: on-failure
    environment:
      - VITE_PROTOCOL=${PROTOCOL}
      - VITE_APP_HOST=${APP_HOST}
    depends_on:
      - backend
    ports:
      - '5173:5173'

  ## NodeJS-Express Backend
  backend:
    container_name: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    #  TODO: Remove ports as soon as nginx setup works?
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app
    restart: on-failure
    environment:
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - GUIDELINES_URL=${GUIDELINES_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PW=${NEO4J_PW}
      - NODE_ENV=${NODE_ENV}
      - PROTOCOL=${PROTOCOL}
      - STYLESHEET_URL=${STYLESHEET_URL}
