version: '3.9'
services:
 ## Nginx Proxy
 #  web:
 #   image: nginx:alpine
 #   volumes:
 #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
 #   #  - ../etc/:/etc/nginx/certs
 #   ports:
 #    - '80:80'
 #    - '443:443'
 #   restart: always
 #   depends_on:
 #    - backend
 #    #  - frontend
 #    - neo4j
 #   environment:
 #    - NGINX_PORT=80
 #   networks:
 #    - intern
 #    - extern

 ## Vue (Nginx) Frontend
 frontend:
  container_name: frontend
  build:
   context: ./client
   dockerfile: Dockerfile
  volumes:
   - ./client:/app
  restart: on-failure
  depends_on:
   - backend
  ports:
   - '5173:5173'

 ## NodeJS-Express Backend
 backend:
  container_name: backend
  build:
   context: ./server
   dockerfile: Dockerfile
  #  TODO: Remove ports as soon as nginx setup works?
  ports:
   - '8080:8080'
  volumes:
   - ./server:/app
  restart: on-failure
  environment:
   - APP_PORT=${APP_PORT}
   - NEO4J_BOLT_PORT=${NEO4J_BOLT_PORT}
   - NEO4J_HTTPS_PORT=${NEO4J_HTTPS_PORT}
   - NEO4J_USER=${NEO4J_USER}
   - NEO4J_PW=${NEO4J_PW}
  depends_on:
   - neo4j

 #  Neo4j Database
 neo4j:
  container_name: neo4j
  image: neo4j:5.19
  restart: unless-stopped
  ports:
   - 7474:7474
   - 7687:7687
  volumes:
   - ./neo4j/plugins:/var/lib/neo4j/plugins
   - ./neo4j/backups:/var/lib/neo4j/backups
   - ./neo4j/data:/data
  environment:
   NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PW}
