export const standoffJson = {
  text: 'Epistula. sancte. hildegardis. ad eundem Lux uiuens dicit. Quendam hominem uidi. quem quasi debilem  ac claudum in precellentia magisterij dimisi. Quomodo? Qui in inbecillitate carnis sue uelut nudi naufragi rebelles erant hos fugit ipse propter timorem belli. Sed nunc  illum uideo sicut humilem et flebilem peregrinum. Vnde illum inspitio uelut filium hereditatis uirga uerberatum! propter inquietudinem morum suorum mentis sue. Uolo autem eum in primitiuam ecclesiam restituere quasi felicem hominem. cum mons in tauro dimergitur. Nunc in eternum uiue.',
  annotations: [
    {
      additionalTexts: [],
      properties: {
        text: 'Epistula. sancte. hildegardis. ad eundem Lux uiuens dicit. Quendam hominem uidi. quem quasi debilem  ac claudum in precellentia magisterij dimisi. Quomodo? Qui in inbecillitate carnis sue uelut nudi naufragi rebelles erant hos fugit ipse propter timorem belli. Sed nunc  illum uideo sicut humilem et flebilem peregrinum. Vnde illum inspitio uelut filium hereditatis uirga uerberatum! propter inquietudinem morum suorum mentis sue. Uolo autem eum in primitiuam ecclesiam restituere quasi felicem hominem. cum mons in tauro dimergitur. Nunc in eternum uiue.',
        startIndex: 0,
        uuid: 'abc123',
        endIndex: 555,
        type: 'p',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'er',
        startIndex: 389,
        originalText: '',
        uuid: 'dfac5103-830f-4782-9625-01cbf422043e',
        endIndex: 390,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'tem',
        startIndex: 438,
        originalText: '',
        uuid: '65cb0b78-b65b-4521-b4ce-4bdab61bd7d2',
        endIndex: 440,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'uirga uerberatum! propter inquietudinem',
        startIndex: 366,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 404,
        uuid: 'e763354d-7352-45ef-a6b3-f57a696eda8b',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'r',
        startIndex: 450,
        originalText: '',
        uuid: '5746a176-9983-4800-93e7-8b65e56cb31b',
        endIndex: 450,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 's',
        startIndex: 235,
        originalText: '',
        uuid: 'ecd82b48-4640-4b64-a0f6-82a4b2543d90',
        endIndex: 235,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'uelut nudi naufragi rebelles erant hos fugit',
        startIndex: 188,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 231,
        uuid: '4af1f1c2-8192-4076-9ea4-c2ddd3e01e17',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'n',
        startIndex: 447,
        originalText: '',
        uuid: 'e001a397-2c80-477e-bd50-92dc1d220977',
        endIndex: 447,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'morum suorum mentis sue. Uolo autem eum',
        startIndex: 406,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 444,
        uuid: '2160b007-b39b-474a-bb50-696b61bb44f1',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'ut',
        startIndex: 286,
        originalText: '',
        uuid: '94bbc11e-4800-4737-94e7-90c73de19481',
        endIndex: 287,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'um',
        startIndex: 409,
        originalText: '',
        uuid: '59f3fa77-d2bc-42a6-951b-0d3710dc6e02',
        endIndex: 410,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'L',
        startIndex: 41,
        subType: 'initial',
        originalText: '',
        uuid: '20c0e3ca-a1d1-4ddf-86de-a322127dc378',
        endIndex: 41,
        type: 'emphasised',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'degardis',
        startIndex: 21,
        originalText: '',
        uuid: 'ceba3e93-095f-46fb-9a0a-3c28fc949960',
        endIndex: 28,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'Epistula. sancte. hildegardis. ad eundem',
        startIndex: 0,
        originalText: '',
        uuid: 'aac2f7ff-8abb-4ef0-92a8-f528cb9efcc4',
        endIndex: 39,
        type: 'head',
      },
      entities: [],
    },
    {
      additionalTexts: [
        {
          annotation: {
            uuid: '977b5da1-5068-43fc-bfb2-7f3a3c3f1938',
            type: 'commentary',
          },
          text: {
            nodeLabels: [],
            data: {
              text: 'Inscritio steht noch in der letzten Zeile des vorherigen Briefes.',
              uuid: '22136d1a-fee4-4219-adde-0ba6540d1052',
            },
          },
        },
      ],
      properties: {
        text: 'Epistula. sancte. hildegardis. ad eundem',
        startIndex: 0,
        originalText: '',
        uuid: '6cabd90e-85a0-421f-975e-24c8b1da6e22',
        endIndex: 39,
        type: 'transposition',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'istu',
        startIndex: 2,
        originalText: '',
        uuid: '8ebba192-69c6-45ba-b1ce-0e9a48c06d2d',
        endIndex: 5,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'm',
        startIndex: 39,
        originalText: '',
        uuid: '3efd3737-d30c-4ac2-8b36-ecc388837016',
        endIndex: 39,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'ncte',
        startIndex: 12,
        originalText: '',
        uuid: 'c28a0184-3f0c-4db3-975e-536a97024d09',
        endIndex: 15,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [
        {
          annotation: {
            uuid: '76cc6690-a640-4d03-93f0-1ab5d6082da7',
            type: 'commentary',
          },
          text: {
            nodeLabels: [],
            data: {
              text: 'Gitterkreuz vor der Initiale',
              uuid: '6735af05-887c-4533-b0b7-0071c277e968',
            },
          },
        },
      ],
      properties: {
        text: 'L',
        startIndex: 41,
        originalText: '',
        uuid: '03767640-37b7-49d7-93d4-86a721c24e0b',
        endIndex: 41,
        type: 'commentary',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'Epistula. sancte. hildegardis. ad eundem',
        startIndex: 0,
        subType: 'rubricated',
        originalText: '',
        uuid: '608028ba-100f-4abc-b669-470d6ed507bc',
        endIndex: 39,
        type: 'emphasised',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'Epistula. sancte. hildegardis. ad eundem',
        startIndex: 0,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 39,
        uuid: '2165586f-6c80-497d-9034-9df503cba9f2',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'ac claudum in precellentia magisterij dimi',
        startIndex: 101,
        firstLineOfPage: true,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 142,
        uuid: '2d6c8b78-ed4d-41e0-9b23-7b66c3f685af',
        firstLineOfColumn: true,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'Lux uiuens dicit. Quendam',
        startIndex: 41,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 65,
        uuid: 'ac72b306-7f94-4462-a285-fee64802acef',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'hominem uidi. quem quasi debilem ',
        startIndex: 67,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: true,
        originalText: '',
        lastLineOfPage: true,
        endIndex: 99,
        uuid: '8cf94a4d-254a-40fb-a60c-44d452220dea',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [
        {
          annotation: {
            uuid: '46dc8331-820c-4bdc-bc8c-4c6e74adca86',
            type: 'commentary',
          },
          text: {
            nodeLabels: [],
            data: {
              text: 'Rasur von ca. 2 Buchstaben, u.U. ac',
              uuid: 'ec8a96c0-88d0-41d7-88c8-9d1eec1bbf29',
            },
          },
        },
      ],
      properties: {
        text: ' ',
        startIndex: 99,
        originalText: '',
        uuid: 'ce1bd2c1-3e33-4e4b-a6a7-c14ccf03a7be',
        endIndex: 99,
        type: 'gap',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'u',
        startIndex: 60,
        originalText: '',
        uuid: '2921ae93-e733-4791-9076-057a1c6f3cf6',
        endIndex: 60,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'm',
        startIndex: 73,
        originalText: '',
        uuid: '109faf02-37c6-49ac-a298-b84426dbc008',
        endIndex: 73,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'n',
        startIndex: 161,
        originalText: '',
        uuid: 'a498b392-7d02-4c2e-beab-1dae3f203f76',
        endIndex: 161,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 's',
        startIndex: 89,
        originalText: '',
        uuid: 'b1eccaed-ddff-471f-97f5-a640f226be94',
        endIndex: 89,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'od',
        startIndex: 151,
        originalText: '',
        uuid: '740c5bef-fe94-4fff-8972-3e238c0b93ad',
        endIndex: 152,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'u',
        startIndex: 87,
        originalText: '',
        uuid: '810ddd69-4140-4d5b-b2a1-5c1971732d50',
        endIndex: 87,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'si. Quomodo? Qui in inbecillitate carnis sue',
        startIndex: 143,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 186,
        uuid: 'a8006734-ae52-4310-853d-c5d30fec3861',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'm',
        startIndex: 65,
        originalText: '',
        uuid: 'e05c958c-fe52-4a32-a86f-508e4896bd8e',
        endIndex: 65,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'in ',
        startIndex: 160,
        subType: 'aboveLine',
        originalText: '',
        uuid: '7f04f49a-2164-49c3-b75f-7c40875f2a92',
        endIndex: 162,
        type: 'nonLinear',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 're',
        startIndex: 116,
        originalText: '',
        uuid: '3c31a253-f265-4504-9a91-160b5ee01c6b',
        endIndex: 117,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'u',
        startIndex: 82,
        originalText: '',
        uuid: '2d9d7be9-acee-4641-8084-4896d8377eea',
        endIndex: 82,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'es',
        startIndex: 464,
        originalText: '',
        uuid: '0c30394d-c627-46b2-81c5-234e51c88f81',
        endIndex: 465,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'er',
        startIndex: 243,
        originalText: '',
        uuid: 'a770221b-57d4-4762-ba85-55b46764ee93',
        endIndex: 244,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'in primitiuam ecclesiam restituere quasi feli',
        startIndex: 446,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 490,
        uuid: '315c0935-806d-4da9-a3a3-80def89a5a0b',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'er',
        startIndex: 373,
        originalText: '',
        uuid: '812a22b7-8440-481c-9632-b59d3861124a',
        endIndex: 374,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'ur',
        startIndex: 530,
        originalText: '',
        uuid: '3c064043-ab6d-46e2-95b3-4b290f4fe46f',
        endIndex: 531,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'u',
        startIndex: 482,
        originalText: '',
        uuid: '6bfb53bf-d8da-46c9-a21e-7659c5c4a499',
        endIndex: 482,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'er',
        startIndex: 544,
        originalText: '',
        uuid: 'e874f668-4bf1-4ac9-96b3-7ae1a2489421',
        endIndex: 545,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [
        {
          annotation: {
            uuid: 'aa3f7872-887d-493b-9e0d-dacbefc59a32',
            type: 'commentary',
          },
          text: {
            nodeLabels: [],
            data: {
              text: 'über den Spaltenrand hinaus geschrieben.',
              uuid: '16b16098-6d93-4606-b643-5a967cf03291',
            },
          },
        },
      ],
      properties: {
        text: 'fugit ',
        startIndex: 227,
        uuid: '82854e17-0acb-4385-9bbd-5c568d2cfc7a',
        endIndex: 232,
        type: 'commentary',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'ro',
        startIndex: 385,
        originalText: '',
        uuid: '0de0e447-a574-4ce5-910a-93bcd167ccb3',
        endIndex: 386,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'gitur. Nunc in eternum uiue.',
        startIndex: 527,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 554,
        uuid: 'e93b8f1b-4dd7-4c54-94ca-5bc039361d84',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'sicut humilem et flebilem peregrinum. Vnde',
        startIndex: 283,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 324,
        uuid: '1ee06f9f-71ce-4bdf-978f-dd99dbc03610',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'ed',
        startIndex: 262,
        originalText: '',
        uuid: 'fb8ec9d4-e770-41e2-b902-41578303add1',
        endIndex: 263,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'er',
        startIndex: 525,
        originalText: '',
        uuid: '16dfed97-5723-422c-b1c2-1884b4d74005',
        endIndex: 526,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'm',
        startIndex: 318,
        originalText: '',
        uuid: '70d71a99-c1b4-419d-bba4-64326db7e479',
        endIndex: 318,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'ipse propter timorem belli. Sed nunc  illum uideo',
        startIndex: 233,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 281,
        uuid: '38755386-c60c-4659-9a3f-346219f6bc0e',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'ro',
        startIndex: 239,
        originalText: '',
        uuid: '43ec76a3-e666-4cd5-bd78-b092061eb0a1',
        endIndex: 240,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'cem hominem. cum mons in tauro dimer',
        startIndex: 491,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 526,
        uuid: '85e1fdd0-b7af-4551-9912-2bf0ada203dc',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'illum inspitio uelut filium hereditatis',
        startIndex: 326,
        firstLineOfPage: false,
        page: '',
        lastLineOfColumn: false,
        originalText: '',
        lastLineOfPage: false,
        endIndex: 364,
        uuid: '4fcfc584-4a4d-4f28-927d-6e7683791ae1',
        firstLineOfColumn: false,
        type: 'line',
        url: '',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'um',
        startIndex: 416,
        originalText: '',
        uuid: 'eeb740e9-1ba7-428d-9e1a-08310ddd1e62',
        endIndex: 417,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'un',
        startIndex: 535,
        originalText: '',
        uuid: '29c583a3-60a0-42fc-84b1-e2a79cebc534',
        endIndex: 536,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 's',
        startIndex: 484,
        originalText: '',
        uuid: '9d930fe7-354f-47a1-935c-41a30eca4ef9',
        endIndex: 484,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'um',
        startIndex: 505,
        originalText: '',
        uuid: '9defc170-71af-4d88-979f-c68329d78065',
        endIndex: 506,
        type: 'expansion',
      },
      entities: [],
    },
    {
      additionalTexts: [],
      properties: {
        text: 'er',
        startIndex: 310,
        originalText: '',
        uuid: '0654d530-5246-418b-893c-f2ec77367c33',
        endIndex: 311,
        type: 'expansion',
      },
      entities: [],
    },
  ],
};
